[versions]
kotlin = "2.2.21"
micronaut = "4.10.8"
micronaut-plugin = "4.6.1"
minestom = "1_21-9219e96f76"
logback = "1.5.21"
shadow-plugin = "9.3.0"
worldseed = "11.5.5"
plasmovoice = "2.1.6"

[libraries]
micronaut-inject = { module = "io.micronaut:micronaut-inject", version.ref = "micronaut" }
micronaut-runtime = { module = "io.micronaut:micronaut-runtime", version.ref = "micronaut" }
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java", version.ref = "micronaut" }

minestom = { module = "net.minestom:minestom-snapshots", version.ref = "minestom" }
worldseed = { module = "net.worldseed.multipart:WorldSeedEntityEngine", version.ref = "worldseed" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

plasmovoice = { module = "su.plo.voice.api:server", version.ref = "plasmovoice" }
plasmovoice-minestom = { module = "su.plo.voice.server:minestom", version.ref = "plasmovoice" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }
